### ISSUE TITLE
Error 500: Please check the filetype and try again

### ISSUE THREAD

**Issue by rajadhee** [sebastianrahtz/oxgarage#12]
1) Installed Ubuntu 16.0.4, 64 bit on server.
2) Installed Java 8, Tomcat 8, Openoffice4.1 as part of the requirement.
3) Followed all the instructions on Github 

Error 500 is generated while accessing ege-webservice/Conversions and ege-webservice/Validation(inspected on browser
![screenshot from 2016-09-22 12-54-49](https://cloud.githubusercontent.com/assets/18632317/18759097/e35a68e6-80c8-11e6-91cb-d3a274d44917.png)
)

Log trace: SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ConversionServlet] in context with path [/ege-webservice] threw exception 
 java.lang.IllegalArgumentException: unknown plug-in ID pl.psnc.dl.ege.root provided for extension point Converter 
	at org.java.plugin.registry.xml.PluginRegistryImpl.getExtensionPoint(PluginRegistryImpl.java:670) 
	at pl.psnc.dl.ege.configuration.EGEConfigurationManager.getAvailableConverters(EGEConfigurationManager.java:248) 
	at pl.psnc.dl.ege.EGEImpl.initialize(EGEImpl.java:120) 
	at pl.psnc.dl.ege.EGEImpl.<init>(EGEImpl.java:109) 
	at pl.psnc.dl.ege.webapp.servlet.ConversionServlet.doGet(ConversionServlet.java:129) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) 
	at

**Comment by jamescummings** [comment]
It is probably better to migrate this issue to https://github.com/TEIC/oxgarage since Sebastian Rahtz has passed away. I don't promise the TEI Consortium (a major user of oxgarage) will fix it, but it is more likely to be seen there.
