### ISSUE TITLE
Exception during the execution an a ege-webservice api call

### ISSUE THREAD

**Issue by alexgenon** [sebastianrahtz/oxgarage#9]
We recently installed Oxgarage on a test server. Specifically, we are trying to install the war on an pre-installed Tomcat server

We followed the instructions on github but, when trying the conversion api using a REST call such as this one : 
`curl -F file=@vo-C-67-23.docx http://localhost:8080/ege-webservice/Conversions/docx%3Aapplication%3Avnd.openxmlformats-officedocument.wordprocessingml.document/TEI%3Atext%3Axml/`

We always get the following exception : 
```
15:51:40,078         INFO TEIConverter:148 - 2015/08/07 15:51:40: Converting FROM:  Documents:Microsoft Word (.docx):docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile null
Exception in thread "Thread-7" java.lang.NoSuchMethodError: net.sf.saxon.Configuration.setProcessor(Ljava/lang/Object;)V
    at net.sf.saxon.s9api.Processor.<init>(Processor.java:60)
    at org.tei.utils.SaxonProcFactory.getProcessor(SaxonProcFactory.java:21)
    at pl.psnc.dl.ege.tei.ComplexConverter.getTEI(ComplexConverter.java:245)
    at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:204)
    at pl.psnc.dl.ege.tei.TEIConverter.transformFromDocX(TEIConverter.java:755)
    at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:199)
    at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:153)
    at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
    at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:44)
    at java.lang.Thread.run(Thread.java:745)
```

We did some investigations and realized that, in the ege-webservice.war, there were 2 jar’s for Saxon library (saxon-8.7.jar and Saxon-HE-9.4.jar) and only Saxon-HE-9.4.jar contained the missing setProcessor method

We tried removing the saxon-8.7.jar and restarting tomcat but then the same call leads to this exception : 
```
09:06:20,291         INFO TEIConverter:148 - 2015/08/11 09:06:20: Converting FROM:  Documents:Microsoft Word (.docx):docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile null
javax.xml.transform.TransformerException: Can't transform a Source of type net.sf.saxon.tree.tiny.TinyDocumentImpl
    at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:418)
    at org.tei.utils.XMLUtils.getXMLNodeAsString(XMLUtils.java:195)
    at org.tei.utils.XMLUtils.storeDocument(XMLUtils.java:52)
    at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:206)
    at pl.psnc.dl.ege.tei.TEIConverter.transformFromDocX(TEIConverter.java:755)
    at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:199)
    at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:153)
    at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
    at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:44)
    at java.lang.Thread.run(Thread.java:745)
```
We tried with both the war from your Jenkins server a war generated on our server using maven.

We tried the conversion using http://oxgarage.oucs.ox.ac.uk:8080/ege-webclient/# and it worked well.

**Comment by sebastianrahtz** [comment]
> On 11 Aug 2015, at 12:53, alexgenon <notifications@github.com> wrote:
> 
> We recently installed Oxgarage on a test server. Specifically, we are trying to install the war on an pre-installed Tomcat server
> 
> We followed the instructions on github but, when trying the conversion api using a REST call such as this one : 
> curl -F file=@vo-C-67-23.docx http://localhost:8080/ege-webservice/Conversions/docx%3Aapplication%3Avnd.openxmlformats-officedocument.wordprocessingml.document/TEI%3Atext%3Axml/
> 
> We always get the following exception :
> 
> 15:51:40,078         INFO TEIConverter:148 - 2015/08/07 15:51:40: Converting FROM:  Documents:Microsoft Word (.docx):docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile null
> Exception in thread "Thread-7" java.lang.NoSuchMethodError: net.sf.saxon.Configuration.setProcessor(Ljava/lang/Object;)V
>     at net.sf.saxon.s9api.Processor.<init>(Processor.java:60)
>     at org.tei.utils.SaxonProcFactory.getProcessor(SaxonProcFactory.java:21)
>     at pl.psnc.dl.ege.tei.ComplexConverter.getTEI(ComplexConverter.java:245)
>     at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:204)
>     at pl.psnc.dl.ege.tei.TEIConverter.transformFromDocX(TEIConverter.java:755)
>     at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:199)
>     at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:153)
>     at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
>     at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:44)
>     at java.lang.Thread.run(Thread.java:745)
> 
> We did some investigations and realized that, in the ege-webservice.war, there were 2 jar’s for Saxon library (saxon-8.7.jar and Saxon-HE-9.4.jar) and only Saxon-HE-9.4.jar contained the missing setProcessor method
> 
> We tried removing the saxon-8.7.jar and restarting tomcat but then the same call leads to this exception :
> 
> 09:06:20,291         INFO TEIConverter:148 - 2015/08/11 09:06:20: Converting FROM:  Documents:Microsoft Word (.docx):docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile null
> javax.xml.transform.TransformerException: Can't transform a Source of type net.sf.saxon.tree.tiny.TinyDocumentImpl
>     at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:418)
>     at org.tei.utils.XMLUtils.getXMLNodeAsString(XMLUtils.java:195)
>     at org.tei.utils.XMLUtils.storeDocument(XMLUtils.java:52)
>     at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:206)
>     at pl.psnc.dl.ege.tei.TEIConverter.transformFromDocX(TEIConverter.java:755)
>     at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:199)
>     at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:153)
>     at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
>     at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:44)
>     at java.lang.Thread.run(Thread.java:745)
> 
> We tried with both the war from your Jenkins server a war generated on our server using maven.
> 
> We tried the conversion using http://oxgarage.oucs.ox.ac.uk:8080/ege-webclient/# and it worked well.
> 
> —
> Reply to this email directly or view it on GitHub.


Sebastian Rahtz      
Director (Research) of Academic IT
University of Oxford IT Services
+44 1865 283431

**Comment by jamescummings** [comment]
It is probably better to migrate this issue to https://github.com/TEIC/oxgarage since Sebastian Rahtz has passed away. I don't promise the TEI Consortium (a major user of oxgarage) will fix it, but it is more likely to be seen there.
